apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: artist-api
  description: API for managing artist information and events
  spec:
    type: openapi
    lifecycle: production
    owner: web-team
    system: event-platform
    definition:
      $text: 'https://gist.githubusercontent.com/lenage/08964335de9064540c8c335fb849c5da/raw/6d63e3546897356882ed7e30cd48891a24e2b354/feature.swagger.json'